#!/usr/bin/env bash
# Phase 1 — Fix licences datasets HF existants
# Pour chaque dataset electron-rare sans cardData.license, push un README.md
# avec frontmatter YAML (license cc-by-sa-4.0 + métadonnées IA Act).

set -u
LOG=~/bench-results/datasets-license-fix.log
TS=$(date +%Y-%m-%dT%H:%M:%S%z)
TMPDIR=$(mktemp -d -t hf-license-fix-XXXXXX)
trap "rm -rf '$TMPDIR'" EXIT

echo "=== Phase 1 license fix start $TS ===" | tee -a "$LOG"

# Réutilise le token HF (export pour hf cli)
export HF_TOKEN=$(cat ~/.cache/huggingface/token)
export HUGGING_FACE_HUB_TOKEN="$HF_TOKEN"

# Map repo -> pretty name + domain tag
declare_repo() { echo "$1|$2|$3"; }
ROWS="$(cat <<EOF
mascarade-stm32-dataset|Mascarade STM32 Dataset|stm32 embedded mcu hal cube
mascarade-spice-dataset|Mascarade SPICE Dataset|spice ngspice circuit-simulation analog
mascarade-iot-dataset|Mascarade IoT Dataset|iot mqtt esp32 lorawan zigbee
mascarade-power-dataset|Mascarade Power Electronics Dataset|power-electronics smps regulator buck-boost
mascarade-dsp-dataset|Mascarade DSP Dataset|dsp signal-processing fir-filter iir-filter fft
mascarade-emc-dataset|Mascarade EMC Dataset|emc emi cispr-25 esd
mascarade-kicad-dataset|Mascarade KiCad Dataset|kicad eda schematic pcb
mascarade-embedded-dataset|Mascarade Embedded Systems Dataset|embedded firmware rtos bare-metal
kill-life-embedded-qa|Kill Life Embedded QA|embedded qa firmware diagnostic kicad
EOF
)"

count=0
# IMPORTANT: read line-by-line, never `for line in $ROWS` (splits on whitespace).
while IFS= read -r line; do
  [ -z "$line" ] && continue
  REPO="${line%%|*}"
  rest="${line#*|}"
  PRETTY="${rest%%|*}"
  TAGS="${rest#*|}"
  count=$((count+1))

  # Vérifie absence de license
  CUR=$(curl -sH "Authorization: Bearer $HF_TOKEN" \
    "https://huggingface.co/api/datasets/electron-rare/$REPO" \
    | python3 -c "import sys,json; print(json.loads(sys.stdin.read()).get('cardData',{}).get('license',''))")
  if [ -n "$CUR" ]; then
    echo "[$REPO] already has license '$CUR' — skip" | tee -a "$LOG"
    continue
  fi

  README="$TMPDIR/$REPO.README.md"
  # Build YAML tags list (one per line, prefixed with "- ")
  TAG_LINES=""
  for t in $TAGS; do
    TAG_LINES+="- $t"$'\n'
  done

  cat > "$README" <<EOF
---
license: cc-by-sa-4.0
language:
- en
- fr
pretty_name: $PRETTY
task_categories:
- text-generation
- question-answering
size_categories:
- 1K<n<10K
tags:
- electronics
- eda
- embedded
$(printf '%s' "$TAG_LINES")---

# $PRETTY

Synthetic instruction-tuning dataset produced by the **Mascarade** pipeline of
the \`electron-rare\` project (Electron Rare). Generated end-to-end with
locally-run open-weight LLMs and curated for downstream fine-tuning of small
electronics-domain assistants.

## License — CC-BY-SA-4.0

This dataset is released under the **Creative Commons Attribution-ShareAlike
4.0 International** license. Derivative works must preserve attribution and
release under a compatible ShareAlike license. This choice is compatible with
the **GPAI Code of Practice (August 2025)** signatories' transparency
expectations.

## EU AI Act compliance notes

- **Provenance**: data generated by Electron Rare's Mascarade pipeline using
  open-weight models (Mistral, Gemma, Qwen, Phi families) running locally on
  Apple Silicon. No proprietary API content.
- **Attribution**: each sample retains generator metadata where available.
- **Risk class**: low — synthetic technical Q&A in the electronics domain.
- **Contact**: clemsail @ huggingface, electron-rare org.

## Citation

\`\`\`bibtex
@dataset{electron_rare_${REPO//-/_}_2026,
  author       = {Electron Rare contributors},
  title        = {$PRETTY},
  year         = {2026},
  publisher    = {Hugging Face},
  url          = {https://huggingface.co/datasets/electron-rare/$REPO}
}
\`\`\`
EOF

  echo "[$REPO] uploading README.md (license=cc-by-sa-4.0)" | tee -a "$LOG"
  if hf upload "electron-rare/$REPO" "$README" "README.md" \
       --repo-type dataset \
       --commit-message "Add CC-BY-SA-4.0 license + EU AI Act dataset card" \
       >> "$LOG" 2>&1; then
    echo "[$REPO] OK" | tee -a "$LOG"
  else
    echo "[$REPO] FAIL (see $LOG)" | tee -a "$LOG"
  fi
done <<< "$ROWS"

echo "=== Phase 1 done — $count datasets processed ===" | tee -a "$LOG"
